---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
ksp <- read.csv("~/Downloads/kickstarter-projects/ks-projects-201801.csv")
View(ksp) 
```


```{r}
sum(is.na(ksp))
str(ksp)
sapply(ksp, function(x) sum(is.na(x)))
sapply(ksp, function(x) sum(is.null(x)))
#usd.pledged has 3797 missing values, so I'm going to delete this columns since there are other columns indicating pledged amount funds. 
```


```{r}
ksp.new <- ksp[-13]
sapply(ksp.new, function(x) sum(is.na(x)))
```

```{r}
ksp.new$state <- ifelse(ksp.new$state == 'successful', 'success', 'fail')
prop.table(table(ksp.new$state))
barplot(prop.table(table(ksp.new$state)))

#Since our target variable is state, I prefer the state variable as binary - either success or fail. 
#35% of projects are successful. There's no difference in proportion after changing the column to binary. 
```
```{r}
prop.table(table(ksp.new$main_category))
barplot(prop.table(table(ksp.new$main_category)), las=2, cex.names = .7)
#The most popular kickstarter project is Film & Video, Music, and Journalism. Let's take a look at their success rate. 
```


```{r}
prop.table(table((ksp.new$state[ksp.new$main_category == 'Film & Video'])))
prop.table(table((ksp.new$state[ksp.new$main_category == 'Music'])))
prop.table(table((ksp.new$state[ksp.new$main_category == 'Publishing'])))

#Music industry has a highest success rate at 46% among three categories.

```



```{r}
prop.table(table(ksp.new$main_category[ksp.new$state=='success']))
barplot(prop.table(table((ksp.new$main_category[ksp.new$state == 'success']))), las=2, cex.names =0.7)
#From the graph, we can tell Music, Film & Video, and Publishing has highest proportion of success among all main categories. 
```


```{r}

```



```{r}

```

